[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://clubhouse.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/user"
  to = "https://clubhouse.herokuapp.com/user"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# [[headers]]
#   for ='/*'
#   [headers.values]
#     Access-Control-Allow-Origin = '*'